# Generated by Django 5.1.7 on 2025-03-27 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_service_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_service_account',
            new_name='service_account',
        ),
    ]
