services:
  user_service:
    build: .
    container_name: sandol_user_service
    ports:
      - "8015:8000"
    volumes:
      - .:/app                # 코드 반영 (선택)
    environment:
      - PYTHONUNBUFFERED=1
