services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    ports:
      - "8080:8080"
    container_name: keycloak
    command: "start-dev"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/testdb
      - KC_DB_USERNAME=localmaster
      - KC_DB_PASSWORD=qwer1234
      # --- 추가: 프록시/서브패스 설정 ---
      - KC_PROXY=edge
      - KC_PROXY_HEADERS=xforwarded
      - KC_HTTP_RELATIVE_PATH=/auth
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HOSTNAME_PATH=/auth
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine3.21
    container_name: postgres
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=localmaster
      - POSTGRES_PASSWORD=qwer1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
